homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 46.3282
  longitude: -119.3222
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 120
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  development: 1
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction


# alexa: !include alexa.yaml

ifttt:
  key: gm_90Mlt3EIMTCUog71DJRK3GQq60QIDHyIcfyBUBD8


# Text to speech
tts:
  platform: google


sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home 
      - type: memory_free
  - platform: yr
  - platform: bitcoin
    display_options:
      - exchangerate
      - trade_volume_btc
  - platform: wunderground
    api_key: f00776522be3ce53
    monitored_conditions:
      - alerts
      - dewpoint_f
      - feelslike_f
      - UV

switch:
  - platform: template
    switches:
      skylight:
        friendly_name: 'Skylight'
        value_template: "{{ is_state('sensor.skylight.state', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.skylight_open
        turn_off:
          service: switch.turn_on
          entity_id: switch.skylight_close

automation:
- alias: Startup Notification
  trigger:
      platform: time
      at: "15:15:00"
  action:
     service: ifttt.trigger
     data: {"event":"HomeAssistant", "value1": "HomeAssistant just got started"}

- alias: 'Change temperature at a certain time'
  trigger:
      platform: time
      at: "15:00:00"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.my_ecobee3
      temperature: 60


# emulated_hue:
#   host_ip: 192.168.1.7
#   listen_port: 8080

# Add nest
# nest:
#   client_id: b0d28a6e-5a93-4ce2-8bf7-aa490bfbdd19
#   client_secret: 3SyJ82GaP6XtrJj2OPNgxnJug

climate:
  platform: demo


ecobee:
  api_key: a7zwoaQrM6IfqrGoI4I8Z7kCPYXCrmSg 

lyric:
  client_id: oZOMRm5ww237ENSSqpGnIwQOzFBhpXoh
  client_secret: bxqSLqpM5wyXIPgu


# media_player:
#   - platform: spotify
#     client_id: 4877546f09434a6fa9216b68d537cc1d
#     client_secret: 276de06184744a06b7be7339ffa79bc9



media_player:
  platform: universal
  name: Test Universal
  children:
    - media_player.living_room_cast
    - media_player.living_room_kodi
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.living_room_tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.living_room_tv
    volume_up:
      service: switch.turn_on
      data:
        entity_id: switch.living_room_volume_up
    volume_down:
      service: switch.turn_on
      data:
        entity_id: switch.living_room_volume_down
    volume_mute:
      service: switch.turn_on
      data:
        entity_id: switch.living_room_mute
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.receiver
        source: '{{ source }}'
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.receiver
        volume_level: '{{ volume_level }}'

  attributes:
    state: switch.living_room_tv
    is_volume_muted: switch.living_room_mute
    volume_level: media_player.receiver|volume_level
    source: media_player.receiver|source
    source_list: media_player.receiver|source_list
# group: !include groups.yaml

logger:

whole_house_energy:
  platform: whole_house_energy_platform

connected_devices:
  platform: connected_devices_platform

transactive_home:
  platform: transactive_platform

advanced_settings:
  platform: advanced_settings_platform

device_statuses:
  platform: device_statuses_platform

user_settings:
  platform: user_settings_platform

group:
  default_view:
    view: yes
    icon: mdi:home 
    entities:
      - transactive_home.transactive_home
      - sun.sun
      - yr.yr
      - sensor.pws_feelslike_f
      - sensor.pws_dewpoint_f
      - sensor.pws_alerts
      - climate.thermostat770c54
      - climate.my_ecobee3
      - sensor.my_ecobee3_humidity
      - sensor.my_ecobee3_temperature
      - binary_sensor.my_ecobee3_occupancy
      - switch.skylight
      - media_player.test_universal
      - sensor.exchange_rate_1_btc
      - sensor.ram_free
      - sensor.disk_use_home
      - sensor.trade_volume
      - climate.heatpump
      - climate.hvac
      - sensor.pws_uv
      - automation.change_temperature_at_a_certain_time
      - automation.startup_notificatio


  Transactive Home:
    view: yes
    icon: mdi:flash
    entities:
      - whole_house_energy.wholehouse_energy_use_and_cost
      - connected_devices.connected_devices



  Setup:
    view: yes
    icon: mdi:settings
    entities:
      - advanced_settings.advanced_settings
      - device_statuses.device_statuses 
      - user_settings.user_settings


