
update_data_privacy:
  description: Update the data privacy setting 

  fields:
    device:
      description: Name of setting to change
      example: 'device1'

    obj:
      description: An object containing the value
      example: 'obj.value'